# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'fire2RTC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'GoogleWebRTC', '~> 1.1'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  # Pods for fire2RTC

end
